### ISSUE TITLE
[Feature request] CURRENT_TIMESTAMP with timezone

### ISSUE THREAD

**Issue by hiroyuki-sato** [muga/embulk-filter-calcite#10] opened 2017-03-21 11:01 UTC
Some users want to generate current timestamp with this plugin.
The `CURRENT_TIMESTAMP` generate the current timestamp.
However,  It generates current timestamp with UTC even if I set `default_timezone`.

The following configuration is the configuration which added the result of `embulk example` output.

```
Tue Mar 21 19:53:04 JST 2017
```

## without timezone

```yaml
filters:
  - type: calcite
#    default_timezone: "Asia/Tokyo"
    query: |-
      select id,CURRENT_TIMESTAMP from $PAGES
```

```
+---------+-----------------------------+
| ID:long | CURRENT_TIMESTAMP:timestamp |
+---------+-----------------------------+
|       1 | 2017-03-21 19:53:25.013 UTC |
|       2 | 2017-03-21 19:53:25.013 UTC |
|       3 | 2017-03-21 19:53:25.013 UTC |
|       4 | 2017-03-21 19:53:25.013 UTC |
+---------+-----------------------------+
```

## With timezone

```yaml
filters:
  - type: calcite
    default_timezone: "Asia/Tokyo"
    query: |-
      select id,CURRENT_TIMESTAMP from $PAGES
```

```
+---------+-----------------------------+
| ID:long | CURRENT_TIMESTAMP:timestamp |
+---------+-----------------------------+
|       1 | 2017-03-21 19:54:08.932 UTC |
|       2 | 2017-03-21 19:54:08.932 UTC |
|       3 | 2017-03-21 19:54:08.932 UTC |
|       4 | 2017-03-21 19:54:08.932 UTC |
+---------+-----------------------------+
```

I expected this result is the `2017-03-21 10:54:08.932`.

## Reference.

I found TIMEZONE property.

https://calcite.apache.org/apidocs/org/apache/calcite/config/CalciteConnectionProperty.html#TIME_ZONE

**Comment by muga** [comment] 2017-03-21 22:27
Thank you, I could reproduce this issue and will fix it.

This issue is not related to `default_timezone` option setting because the option is from embulk-input-jdbc's ColumnSetterFactory. Sorry to you confused. (I think that it's better to hide the option to avoid any confusing. )

**Comment by hiroyuki-sato** [comment] 2017-03-21 23:46
Thank you for the comment.

I found the following JIRA.
https://issues.apache.org/jira/browse/CALCITE-964

And the following patch worked as I expected.


```diff
diff --git a/src/main/java/org/embulk/filter/calcite/CalciteFilterPlugin.java b/src/main/java/org/embulk/filter/calcite/CalciteFilterPlugin.java
index 58345aa..fc47994 100644
--- a/src/main/java/org/embulk/filter/calcite/CalciteFilterPlugin.java
+++ b/src/main/java/org/embulk/filter/calcite/CalciteFilterPlugin.java
@@ -119,6 +119,7 @@ public class CalciteFilterPlugin
             // Relax case-sensitive
             // @see https://calcite.apache.org/docs/adapter.html#jdbc-connect-string-parameters
             props.setProperty("caseSensitive", "false");
+            props.put("timeZone", "UTC");
             return new Driver().connect(jdbcUrl, props);
         }
         catch (SQLException e) {
```

```
Wed Mar 22 08:44:50 JST 2017
```

```
+---------+-----------------------------+
| ID:long | CURRENT_TIMESTAMP:timestamp |
+---------+-----------------------------+
|       1 | 2017-03-21 23:43:32.115 UTC |
|       2 | 2017-03-21 23:43:32.115 UTC |
|       3 | 2017-03-21 23:43:32.115 UTC |
|       4 | 2017-03-21 23:43:32.115 UTC |
+---------+-----------------------------+
```

**Comment by muga** [comment] 2017-03-22 00:21
@hiroyuki-sato Cool. Thank you for investigating. The fix might work for us. I also will check the source code of Apache Calcite and then, fix and release new version.

**Comment by muga** [comment] 2017-03-22 08:27
Fix it on https://github.com/muga/embulk-filter-calcite/pull/11

**Comment by muga** [comment] 2017-03-23 06:42
#11 was merged into master. I will release new version soon.

**Closed as completed by muga** 2017-03-23 06:42 UTC
